version: "3.9"

services:
  db:
    container_name: motors_shop
    image: postgres:12
    ports:
      - 45432:5432
    environment:
      - POSTGRES_USER=daniele
      - POSTGRES_PASSWORD=9543
      - POSTGRES_DB=motors_shop
