version: "3.9"

services:
  db:
    container_name: motors_shop
    image: postgres:12
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=environment.POSTGRES_USER
      - POSTGRES_PASSWORD=environment.POSTGRES_PASSWORD
      - POSTGRES_DB=environment.POSTGRES_DB
